import java.io.*;
import java.util.*;

class Main {
    static final long MOD = 998244353;

    // Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        long L;
        L = sc.nextLong();
        String[] S = new String[(int)(N)];
        for(int i = 0 ; i < N ; i++){
            S[i] = sc.next();
        }
        solve(N, L, S);
    }

    static void solve(long N, long L, String[] S){

    }
}
