import java.io.*;
import java.util.*;

class Main {
    static final long MOD = 998244353;

    // Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long R;
        R = sc.nextLong();
        long G;
        G = sc.nextLong();
        long B;
        B = sc.nextLong();
        long K;
        K = sc.nextLong();
        long X;
        X = sc.nextLong();
        long Y;
        Y = sc.nextLong();
        long Z;
        Z = sc.nextLong();
        solve(R, G, B, K, X, Y, Z);
    }

    static void solve(long R, long G, long B, long K, long X, long Y, long Z){

    }
}
