import java.io.*;
import java.util.*;

class Main {
    static final long MOD = 1000000007;

    // Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        String[] c = new String[(int)(N)];
        for(int i = 0 ; i < N ; i++){
            c[i] = sc.next();
        }
        long[] a = new long[(int)(N-1)];
        long[] b = new long[(int)(N-1)];
        for(int i = 0 ; i < N-1 ; i++){
            a[i] = sc.nextLong();
            b[i] = sc.nextLong();
        }
        solve(N, c, a, b);
    }

    static void solve(long N, String[] c, long[] a, long[] b){

    }
}
