import java.io.*;
import java.util.*;

class Main {

    // Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long[] r = new long[(int)(2)];
        long[] c = new long[(int)(2)];
        for(int i = 0 ; i < 2 ; i++){
                r[i] = sc.nextLong();
                c[i] = sc.nextLong();
        }
        solve(r, c);
    }

    static void solve(long[] r, long[] c){

    }
}
