import java.io.*;
import java.util.*;

class Main {

    // Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        long K;
        K = sc.nextLong();
        long[] x = new long[(int)(N)];
        long[] y = new long[(int)(N)];
        String[] c = new String[(int)(N)];
        for(int i = 0 ; i < N ; i++){
                x[i] = sc.nextLong();
                y[i] = sc.nextLong();
                c[i] = sc.next();
        }
        solve(N, K, x, y, c);
    }

    static void solve(long N, long K, long[] x, long[] y, String[] c){

    }
}
