import java.io.*;
import java.util.*;

class Main {

    // Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        long[][] A = new long[(int)(N)][(int)(N)];
        for(int i = 0 ; i < N ; i++){
            for(int j = 0 ; j < N ; j++){
                A[i][j] = sc.nextLong();
            }
        }
        long M;
        M = sc.nextLong();
        long[] X = new long[(int)(M)];
        long[] Y = new long[(int)(M)];
        for(int i = 0 ; i < M ; i++){
            X[i] = sc.nextLong();
            Y[i] = sc.nextLong();
        }
        solve(N, A, M, X, Y);
    }

    static void solve(long N, long[][] A, long M, long[] X, long[] Y){

    }
}
