import java.io.*;
import java.util.*;

class Main {

    // Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        long A_x;
        A_x = sc.nextLong();
        long A_y;
        A_y = sc.nextLong();
        long B_x;
        B_x = sc.nextLong();
        long B_y;
        B_y = sc.nextLong();
        String[] S = new String[(int)(N)];
        for(int i = 0 ; i < N ; i++){
            S[i] = sc.next();
        }
        solve(N, A_x, A_y, B_x, B_y, S);
    }

    static void solve(long N, long A_x, long A_y, long B_x, long B_y, String[] S){

    }
}
