import java.io.*;
import java.util.*;

class Main {

    // Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long W;
        W = sc.nextLong();
        long N;
        N = sc.nextLong();
        long[] L = new long[(int)(N)];
        long[] R = new long[(int)(N)];
        for(int i = 0 ; i < N ; i++){
            L[i] = sc.nextLong();
            R[i] = sc.nextLong();
        }
        solve(W, N, L, R);
    }

    static void solve(long W, long N, long[] L, long[] R){

    }
}
