import java.io.*;
import java.util.*;

class Main {

    // Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        long Q;
        Q = sc.nextLong();
        long[] T = new long[(int)(Q)];
        long[] X = new long[(int)(Q)];
        long[] Y = new long[(int)(Q)];
        long[] V = new long[(int)(Q)];
        for(int i = 0 ; i < Q ; i++){
            T[i] = sc.nextLong();
            X[i] = sc.nextLong();
            Y[i] = sc.nextLong();
            V[i] = sc.nextLong();
        }
        solve(N, Q, T, X, Y, V);
    }

    static void solve(long N, long Q, long[] T, long[] X, long[] Y, long[] V){

    }
}
