import java.io.*;
import java.util.*;

class Main {
    static final long MOD = 998244353;

    // Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        long Q;
        Q = sc.nextLong();
        String S;
        S = sc.next();
        long[] x = new long[(int)(Q)];
        String[] c = new String[(int)(Q)];
        for(int i = 0 ; i < Q ; i++){
            x[i] = sc.nextLong();
            c[i] = sc.next();
        }
        solve(N, Q, S, x, c);
    }

    static void solve(long N, long Q, String S, long[] x, String[] c){

    }
}
