import java.io.*;
import java.util.*;

class Main {
    static final long MOD = 2;
    static int count = 0;

    // Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools (tips:
    // You use the default template now. You can remove this line by using your
    // custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        long[] A = new long[(int) (N)];
        for (int i = 0; i < N; i++) {
            A[i] = sc.nextLong();
        }
        solve(N, A);
        System.out.println(count);
    }

    static void solve(long N, long[] A) {
        for (int i = 0; i < N; i++) {
            if (A[i] % 2 == 0) {
                A[i] = A[i] / 2;
            } else {
                break;
            }
            if (i == N - 1) {
                count++;
                solve(N, A);
            }
        }
    }
}
