import java.io.*;
import java.util.*;

class Main {

    // Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools (tips:
    // You use the default template now. You can remove this line by using your
    // custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        int A;
        A = sc.nextInt();
        int B;
        B = sc.nextInt();
        int C;
        C = sc.nextInt();
        int X;
        X = sc.nextInt();
        solve(A, B, C, X);
    }

    static void solve(int A, int B, int C, int X) {
        int count = 0;
        for (int i = 0; i <= A; i++) {
            for (int j = 0; j <= B; j++) {
                int sum = (X - (500 * i) - (100 * j)) / 50;
                if (sum >= 0 && sum <= C) {
                    count++;
                }

            }
        }
        System.out.println(count);
    }
}
