import java.io.*;
import java.util.*;

class Main {
    static final String YES = "Yes";
    static final String NO = "No";

    // Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        long T;
        T = sc.nextLong();
        long[] AX = new long[(int)(N)];
        long[] AY = new long[(int)(N)];
        for(int i = 0 ; i < N ; i++){
            AX[i] = sc.nextLong();
            AY[i] = sc.nextLong();
        }
        long[] BX = new long[(int)(N)];
        long[] BY = new long[(int)(N)];
        for(int i = 0 ; i < N ; i++){
            BX[i] = sc.nextLong();
            BY[i] = sc.nextLong();
        }
        solve(N, T, AX, AY, BX, BY);
    }

    static void solve(long N, long T, long[] AX, long[] AY, long[] BX, long[] BY){

    }
}
