import java.io.*;
import java.util.*;

class Main {

    // Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        long K;
        K = sc.nextLong();
        long[] X = new long[(int)(N)];
        long[] Y = new long[(int)(N)];
        for(int i = 0 ; i < N ; i++){
            X[i] = sc.nextLong();
            Y[i] = sc.nextLong();
        }
        solve(N, K, X, Y);
    }

    static void solve(long N, long K, long[] X, long[] Y){

    }
}
