import java.io.*;
import java.util.*;

class Main {
    static final String YES = "Yes";
    static final String NO = "No";

    // Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        long[] t = new long[(int)(N)];
        long[] x = new long[(int)(N)];
        long[] y = new long[(int)(N)];
        for(int i = 0 ; i < N ; i++){
                t[i] = sc.nextLong();
                x[i] = sc.nextLong();
                y[i] = sc.nextLong();
        }
        solve(N, t, x, y);
    }

    static void solve(long N, long[] t, long[] x, long[] y){

    }
}
