import java.io.*;
import java.util.*;

class Main {
    static final long MOD = 1000000007;

    // Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        long[][] A = new long[(int)(N)][(int)(6)];
        for(int i = 0 ; i < N ; i++){
            for(int j = 0 ; j < 6 ; j++){
                A[i][j] = sc.nextLong();
            }
        }
        solve(N, A);
    }

    static void solve(long N, long[][] A){

    }
}
