import java.io.*;
import java.util.*;

class Main {

    // Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long X;
        X = sc.nextLong();
        long A;
        A = sc.nextLong();
        long B;
        B = sc.nextLong();
        solve(X, A, B);
    }

    static void solve(long X, long A, long B){

    }
}
