import java.io.*;
import java.util.*;

class Main {

    // Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools (tips:
    // You use the default template now. You can remove this line by using your
    // custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        int N;
        N = sc.nextInt();
        Integer[] a = new Integer[(int) (N)];
        for (int i = 0; i < N; i++) {
            a[i] = sc.nextInt();
        }
        solve(N, a);
    }

    static void solve(int N, Integer[] a) {
        int sumA = 0;
        int sumB = 0;
        Arrays.sort(a, Collections.reverseOrder());
        for (int i = 0; i < N; i++) {
            if (i % 2 == 0) {
                sumA += a[i];
            } else {
                sumB += a[i];
            }
        }
        int subAB = sumA - sumB;
        System.out.println(subAB);
    }
}
