import java.io.*;
import java.util.*;

class Main {
    static final String YES = "Yes";
    static final String NO = "No";

    // Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        long[] A = new long[(int)(N)];
        for(int i = 0 ; i < N ; i++){
            A[i] = sc.nextLong();
        }
        solve(N, A);
    }

    static void solve(long N, long[] A){

    }
}
