import java.io.*;
import java.util.*;

class Main {

    // Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        long[] A = new long[(int)(N-2+1)];
        for(int i = 0 ; i < N-2+1 ; i++){
            A[i] = sc.nextLong();
        }
        long[] u = new long[(int)(N-1)];
        long[] v = new long[(int)(N-1)];
        for(int i = 0 ; i < N-1 ; i++){
            u[i] = sc.nextLong();
            v[i] = sc.nextLong();
        }
        solve(N, A, u, v);
    }

    static void solve(long N, long[] A, long[] u, long[] v){

    }
}
