import java.io.*;
import java.util.*;

class Main {

    // Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long Q;
        Q = sc.nextLong();
        long[] t = new long[(int)(Q)];
        long[] x = new long[(int)(Q)];
        for(int i = 0 ; i < Q ; i++){
            t[i] = sc.nextLong();
            x[i] = sc.nextLong();
        }
        solve(Q, t, x);
    }

    static void solve(long Q, long[] t, long[] x){

    }
}
