import java.io.*;
import java.util.*;

class Main {
    static final long MOD = 1000000007;

    // Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        long B;
        B = sc.nextLong();
        long K;
        K = sc.nextLong();
        long[] c = new long[(int)(K)];
        for(int i = 0 ; i < K ; i++){
            c[i] = sc.nextLong();
        }
        solve(N, B, K, c);
    }

    static void solve(long N, long B, long K, long[] c){

    }
}
