import java.io.*;
import java.util.*;

class Main {
    static final String YES = "Yes";
    static final String NO = "No";

    // Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long[][] c = new long[(int)(3)][(int)(3)];
        for(int i = 0 ; i < 3 ; i++){
                for(int j = 0 ; j < 3 ; j++){
                    c[i][j] = sc.nextLong();
                }
        }
        solve(c);
    }

    static void solve(long[][] c){

    }
}
