import java.util.*;

class Main {

    // Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long A;
        A = sc.nextLong();
        long B;
        B = sc.nextLong();
        solve(A, B);
    }

    static void solve(long A, long B){
        double d = Math.sqrt(A*A+B*B);
        double dA = A/d;
        double dB = B/d;
        System.out.println(dA+" " +dB);
    }
}
