import java.io.*;
import java.util.*;

class Main {

    // Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        long H;
        H = sc.nextLong();
        long[] a = new long[(int)(N)];
        long[] b = new long[(int)(N)];
        for(int i = 0 ; i < N ; i++){
                a[i] = sc.nextLong();
                b[i] = sc.nextLong();
        }
        solve(N, H, a, b);
    }

    static void solve(long N, long H, long[] a, long[] b){

    }
}
