import java.io.*;
import java.util.*;

class Main {

    // Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        long[][] A = new long[(int)(2)][(int)(N)];
        for(int i = 0 ; i < 2 ; i++){
                for(int j = 0 ; j < N ; j++){
                    A[i][j] = sc.nextLong();
                }
        }
        solve(N, A);
    }

    static void solve(long N, long[][] A){

    }
}
