import java.io.*;
import java.util.*;

class Main {

    // Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools (tips:
    // You use the default template now. You can remove this line by using your
    // custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        int N;
        N = sc.nextInt();
        int Y;
        Y = sc.nextInt();
        solve(N, Y);
    }

    static void solve(int N, int Y) {
        int y = Y / 1000;

        for (int a = 0; a <= N; a++) {
            for (int b = 0; b <= N - a; b++) {
                int c = N - a - b;
                int sum = a * 10 + b * 5 + c;
                if (sum == y) {
                    System.out.println(a + " " + b + " " + c);
                    return;
                }
            }
        }
        System.out.println("-1 -1 -1");
    }
}
