import java.io.*;
import java.util.*;

class Main {
    static final String NO = "Impossible";

    // Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        long S;
        S = sc.nextLong();
        long[] A = new long[(int)(N)];
        long[] B = new long[(int)(N)];
        for(int i = 0 ; i < N ; i++){
            A[i] = sc.nextLong();
            B[i] = sc.nextLong();
        }
        solve(N, S, A, B);
    }

    static void solve(long N, long S, long[] A, long[] B){

    }
}
