import java.io.*;
import java.util.*;

class Main {

    // Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools (tips:
    // You use the default template now. You can remove this line by using your
    // custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        int N;
        N = sc.nextInt();
        int A;
        A = sc.nextInt();
        int B;
        B = sc.nextInt();
        solve(N, A, B);
    }

    static void solve(int N, int A, int B) {
        int sum = 0;
        for (int i = 1; i <= N; i++) {
            int targetNumber = i;
            int sumDigits = 0;

            while (targetNumber > 0) {
                sumDigits += targetNumber % 10;
                targetNumber /= 10;
            }

            if (A <= sumDigits && sumDigits <= B) {
                sum += i;
            }

        }
        System.out.println(sum);
    }
}
