import java.io.*;
import java.util.*;

class Main {
    static final String YES = "Yes";
    static final String NO = "No";

    // Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        long M;
        M = sc.nextLong();
        long Q;
        Q = sc.nextLong();
        long[] X = new long[(int)(M)];
        long[] Y = new long[(int)(M)];
        for(int i = 0 ; i < M ; i++){
            X[i] = sc.nextLong();
            Y[i] = sc.nextLong();
        }
        long[] A = new long[(int)(Q)];
        long[] B = new long[(int)(Q)];
        for(int i = 0 ; i < Q ; i++){
            A[i] = sc.nextLong();
            B[i] = sc.nextLong();
        }
        solve(N, M, Q, X, Y, A, B);
    }

    static void solve(long N, long M, long Q, long[] X, long[] Y, long[] A, long[] B){

    }
}
