import java.io.*;
import java.util.*;

class Main {

    // Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long N;
        N = sc.nextLong();
        long[] lx = new long[(int)(N)];
        long[] ly = new long[(int)(N)];
        long[] rx = new long[(int)(N)];
        long[] ry = new long[(int)(N)];
        for(int i = 0 ; i < N ; i++){
            lx[i] = sc.nextLong();
            ly[i] = sc.nextLong();
            rx[i] = sc.nextLong();
            ry[i] = sc.nextLong();
        }
        solve(N, lx, ly, rx, ry);
    }

    static void solve(long N, long[] lx, long[] ly, long[] rx, long[] ry){

    }
}
