import java.io.*;
import java.util.*;

class Main {

    // Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long T;
        T = sc.nextLong();
        long L;
        L = sc.nextLong();
        long X;
        X = sc.nextLong();
        long Y;
        Y = sc.nextLong();
        long Q;
        Q = sc.nextLong();
        long[] E = new long[(int)(Q)];
        for(int i = 0 ; i < Q ; i++){
            E[i] = sc.nextLong();
        }
        solve(T, L, X, Y, Q, E);
    }

    static void solve(long T, long L, long X, long Y, long Q, long[] E){

    }
}
